version: '3'
services:
  nginx:
    # as nginx is the main router of this application we are adding "restart=always", to ensure it is always ON
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      # we configured nginx to listen to port 80 internally
      # so we are mapping 3050 to 80
      # port 3050 is where the app is going to be available on the localhost
      - '3050:80'
  postgres: 
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    build:
      # just let it know the file name, the folder (path) will come from "context" property
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # this tells docker - do not touch the contents of "/app/node_modules"  
      - /app/node_modules
      # copy all from "./server" into "./app" inside the container
      - ./server:/app
    environment:
      # in this case the values are setup by us in keys.js file, and as the key we specify just the service name from this (docker-compose.yml) file
      - REDIS_HOST=redis
      # it is redis default port:
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379